---
title: "Miranda Fricker's Epistemic Injustice"
subtitle: "A Robust Analysis"
date: '2026-01-06'
---

There is a distinctive kind of epistemic harm/injustice that consists undermining our ability to convey knowledge to others and make sense of our own experiences [@fric07].

Miranda @fric07 argues that social power is a socially situated capacity to control other's actions. Sometimes this social power is exercised in a way to create prejudicial stereotypes, distorting a hearer's credibility judgments. A virtuous hearer is one who reliably corrects for the influence of prejudice in her credibility judgments.

Therefore, virtuous testimonial injustice corrects for the influence of identity prejudice. By emplooying an originalist, state of nature, epistemic virtue is a natural normal source of knowledge. Recognizing the originalist position of epistemic virtue then, epistemic objectification is seen as exclusionary and undercuts understanding and knowledge. This exclusion undercuts the victim's ability to understand themselves since they are unable to participate in practices through which social emanings are generated.

Power is a social capacity/agency. It is a kind of agency that fortifies the ability of its host to influence what happens in the world. There are two ways to exercise this agency, human or structural. We can imagine a person who is able to convince a jury that a crime occured. But the human capacity is dependent on a structure that enables the human to articulate his argument in a way that does not distort it. For instance, we can imagine a human that is relying on FaceBook's algorithm, but this algorithm is biased against him in someway. It doesn't share his posts with the right audience, etc. Therefore human agency is in someway structural. But at the same time, structural agency is merely structural human agency, at the end of the day, some human created the structural algorithm.

Additionally, the kinds of events that we care most about, are those that occur in the social realm and there are two ways to make these kinds of events occur, through active human agency, or passive structural agency. Therefore power, human or structural, is social power and its agents are social agents and the hosts of social power are social agents.

But who are these agents? Those who are agents are those for whom society imagines to be endowed with a special kind of agency. For instance, a police officer is a person whom society imagines to be endowed with a characteristic social power. This power comes from an additional imagination such that that individual who is a police officer, is somehow deserving of this power.

For instance, we might believe that they possess enough self-control such that they are allowed to carry firearms. An example used by Fricker is of gender identities. The social imagination female identities is such that such individuals who inhabit such identities are thought to be less credible on various issues. In contrast, those individuals who inhabit the police officer identity is thought to be more credible on various issues, for instance direct testimony.

Therefore the central cases of testimonial injustice is prejudicial and consists in credibility excesses and deficits where we give more credibility to some identities and less to others.

Fricker argues in the second chapter that prejudice is made possible through stereotypes [For instance, see @kahn82]. These stereotypes persist through the social imagination, but more importantly is a question about their source. A form of agency then involves the ability of an individual or group of individuals to infuse the social imagination with stereotypes.
