---
title: "The Nature of Fiction, Gregory Currie"
#subtitle: "The manticore as a beast of burden"
date: '2025-12-18'
---

# Concept of Fiction

1. How do we come to have the kind of fiction that we do?
2. How is fiction made possible?
   1. What are the characteristics that distinguish fiction from non-fiction?
   2. What sorts of entities make fiction possible?
   3. What psychological and linguistic resources must producers and consumers of fiction have access to?

## Fiction and Language

1. Fiction uses language.
2. But there is no universal linguistic feature shared by all fictional works and there is no available proof confirming what is a fiction. [Modern schools of criticism, Terry Eagleton, Literary Theory, 1983; Russian Formalists, L.T. Lemon and MJ Reis, Russian Formalist Criticism: Four Essays, 1965; on Structuralism, see Jonathan Culler, Structuralist Poetics, 1975; New Criticism, see Cleanth Brooks, The Well-Wrought Urn, 1949.]
3. However, reading a work is an act of reading words and sentences that make it up. [Anatomy of Criticism, 1975, 122]
4. Therefore what makes something a fiction is neither a necessary nor sufficient condition for being fictional.
5. and Therefore something is determined to be a fiction by it's verbal structure but what makes it a fiction does not lie in the text itself.

## Semantic Properties

1. Fictionality is a relational property, it is something possessed in virtue of the text's relations to other things.
2. Therefore it is possible that fictionality is a linguistic matter. (a method of communication, communicative practice)
3. Fictional, like non-fictional texts have the semantic properties of truth value and reference.

## Readers and Authors

## The Pretense Theory

## Make-Believe

## The Author's Intentions

## Communicative Acts

## Fictive Communication

## Objections to the Necessity of the Analysis

## Objections to the Sufficiency of the Analysis

## Make-Believe and Pretense

# Structure of Stories

## Truth in fiction and fictional worlds

## Being fictional

## Lewis's theory

## More on make-believe

## Truth in fiction and belief

## Fictional author and informed reader

## Strategies of interpretation

## Fictional to a degree?

## Fictions in visual media

# Interpretation

## Relationalism and relativism

## The intentional fallacy

## Intentional meaning and conventional meaning

## The return of the author

## The text

## Story and style

## Fictional author and narrator

# The Characters of Fiction

## Fictional names and proper names

## Existent and nonexistent things

## Reference fixing and descriptive names

## Transworld identity and counterpart theory

## Diagonal propositions

## The content of make-believe

## In defense of the fictional author

## The metafictive use of fictional names

## Accidental reference and aboutness

## Fictional names and singular propositions

## Roles

## Conclusions

# Emotion and the Response to Fiction

## Finding the problem

## The options

## A theory of emotion

## A solution

## Objections and revisions

## Alternatives

## One solution or two?

## Emotional congruence

## Psychological kinds
