---
title: "Serious Games"
date: '2025-10-12'
---

* 5 characteristics of games/serious games
  * Goal
  * Rules
  * Feedback
  * Voluntary participation
  * Competition

* Play
  * Free activity
  * Not Meant
  * Immersive
  * Boundaries of time and space
  * Rules
  * Creates order

Function of Play:

Enhance our adaptive variability: Play helps us to acquire specific skills, and makes us more flexible to deal with changing circumstances in our lives.

## Why are games enjoyable?

Functional, cognitive development

Social development

Functionality of play with rewards of games reason why we play games.

## Seven Motivations

1. Control
2. Challenge
3. Competition
4. Fantasy: can be a laboratory to test player "The game functions as a kind of laboratory for people to test behavior and emotions.
5. Interest
6. Diversion
7. Social interaction

### Self Determination Theory

1. Autonomy: Self organize experience: gives feeling of autonomy
2. Competence challenge: makes them feel competent
3. Relatedness, connection: makes them feel related to others

Deci & Ryan
