---
title: "Hermeneutic Marginalization"
subtitle: "The manticore as a beast of burden"
date: '2025-12-06'
---

In medieval bestiaries, there are two classes of evil represented by beasts; those which deceive and those which generate fear and death [@pine21]. These two characterizations are used by artistic means for educating the general populations of the Middle Ages. More specifically, the purpose of this education is for orthodoxy, and is intended to promote proper behavior and right action. Among the first class of beasts, those which are notable for their abilities to deceive, there are three kinds of deception: these are noted by the camouflages of the chameleon, accurate imitations of the manticore, and the "seductive skills of sirens". While we might think this to be a medieval taxonomy of epistemic harms only, the kinds of epistemic harms the medievalists worried about are not far off from contemporary epistemic harms and risks; misinformation, false and inauthentic narratives, and bullshit.

In her book *Epistemic Injustice*, @fric07 defines hermeneutic injustice as a gap in collective interpretive resources that hinder a person's ability to make sense of their own experiences. This is more akin to the kind of evil that deceives. There is good reason to think that hermeneutic injustice is not solely a modern evil, that if Fricker is correct, then there would be motivation to restrict a group's hermeneutic participation in social life. Historically, this injustice was committed against women, but there is not much reason to think that it was committed only against women. As a more general injustice then, this is a source of evil in that it is an experience that is direct and intuited by the victim of the evil [@russ16, 1]. More specifically, it is a representation of one kind of epistemic harm. However, it is not particularly just which kind of epistemic harm the manticore represents. Beastiaries of early Europe can perhaps provide something of an early classification of epistemic harms such as misinformation, gaslighting, and bullshit.

## Hermeneutic Marginalization

> "Beastiaries are composed of different hermeneutic codes which are mapped to different sensitive levels, that is, from the level describing mere anatomy we may turn to the one dealing with ethical-philosophical consideration; and further turn to the one on moral perspectives which are later complemented with the theological ones (Voisenet 2020, pp. 321–25). In all these cases, the fields of word and those of image are intertwined (Kay 2017). In the end, XII–XIII century bestiaries, books on natural history and encyclopedias allow us to access a world where both the creative power of goodness and evil are present: The excellence of divine creation and the subtlety of diabolic action play a role."

### Types of hermeneutic codes

* 'Mere' anatomy
* Ethical-philosophical considerations
* Moral perspectives
* Theological perspectives

What is a hermeneutic code in these cases?

A way to understand this may be arts divergent foci on simple reality and complex reality. Between these two representations is a set of norms culturally and socially constructed to guide the representation of the human condition: experience, knowledge, and beliefs. The conflict here is between God and the devil. What specifically are the adverse actions, carried out by the one against the other in this space? Jesus' death, burial, and resurrection is at one level an adverse action carried out by the work of the devil, yet at the same time, it is also symbolic of the ultimate victory, that of God over sin, death, hell, and the grave.

> "Its commitment with reality is undeniable yet the reality which it at
tempts to represent is so complex and vast that the limits between what is and what is not,
between what we believe and what we know, between what we are and what we wish to
be, are often blurred (Cronin 1941). Medieval ars is much more than a set of norms which
ought to be followed to produce something that can be called art. "

> "Art, so understood, is a necessary element in the configuration of human
condition in terms of experience, knowledge, and beliefs.
It is within this context where the action of God and that of the devil provide one of
the most profound lectures of reality."
