---
title: "Ryan Peterson on the Imago Dei"
subtitle: "and Human Identity"
date: '2026-01-15'
categories: ["metaphysics"]
pub_number: 96
---

1. A theology of the imago dei
2. Is image substance, function, or relationship?
3. Image as Identity
4. Revelatory or Canonical Interpretation of the Imago Dei
5. The Canonical Imago Dei
6. The Identity Interpretation and the Christian Tradition

# 1 A theology of the imago Dei

"The imago dei is humanity's identity", namely an identity that is "basic to all human existence" [1]. According to this interpretation of the creation account, humanity was created to serve as an earthly image of God, "God in the world". As such, attributes of God, are synonymous with human attributes. Why don't we exhibit these attributes then, but instead exhibit other more reprehensible ones?

# 2 Image, Substance, Function, or Relationship

1. Thomas Aquinas: substantialistic
2. Karl Barth: relational interpretation
3. J. Richard Middleton: functional interpretation

# 3 Image as identity

1. Imago Dei and Identity
2. The imago Dei is human identity
3. Imago Dei and personhood, substance, function, and relations

## Presuppositions

1. Identity: strong, corporate, according to which imago Dei = common identity shared by all individual human beings.
2. Knowledge: meaning of imago Dei acquired on the basis of the narrative identity of human develped wihtin the OT and NT bibilical literature
3. Like Jesus's divine identity, human  identity is discerned parallel through careful attention to specific portrayal of identity in relevant biblical texts.

### Common Uses of Identity

1. Quality or condition of being the same in substance, composition, nature, properties, or in particular quarlities under consideration; absolute or essential sameness: oneness
2. The sameness of a person or thing at all times or in all circumstances; the condition or fact that a person or thing is itself and not something selse; individuality, personality

Peterson uses 2:

> the condition or fact that person or thing is itself and not something else

That condition that distinguishes humans from all other creatures.

### Identity in the Social Sciences

Rogers Brubaker and Frederick Cooper:

1. basis for social or political action
   1. understanding and self-interest
   2. particularity and (putative) universality
   3. two ways of construing social location
2. collective phenomenon
   1. social movements
   2. gender, race, ethnicity, nationalism
3. core aspect
   1. self-hood
   2. social being
4. social or political action
   1. interactive development of collective self-understanding
   2. solidarity
   3. groupness that makes collective action possible
5. Multiple and competing discourses
   1. unstable, multiple, fluctuating, and fragmented nature of contemporary self
   2. Foucault, post-structuralism, and post-modernism
   3. ethnicity, i.e., situationlist or contextualist accounts of ethnicity
