---
title: "Aesthetics of Evil"
#subtitle: ""
date: '2026-01-31'
---

In medieval bestiaries, there are two classes of evil represented by beasts; those which deceive and those which generate fear and death. Among the first class of beasts, those which are notable for their abilities to deceive, there are three kinds of deception: these are noted by the camouflages of the chameleon, accurate imitations of the manticore, and the "seductive skills of sirens". While we might think this to be a medieval taxonomy of epistemic harms only, the kinds of epistemic harms the medievalists worried about are not far off from contemporary epistemic harms and risks; misinformation, false and inauthentic narratives, and bullshit.

There are two kinds of beasts representing evil in medieval beastiaries; those that deceive and those that cause fear and death [@pine21]. These two characterizations are used by artistic means for educating the illiterate populations of the Middle Ages. More specifically, the purpose of this education is for orthodoxy, it is intended to promote proper behavior and right action.

In her book *Epistemic Injustice*, @fric07 defines hermeneutic injustice as a gap in collective interpretive resources that hinder a person's ability to make sense of their own experiences. This is more akin to the kind of evil that deceives. There is good reason to think that hermeneutic injustice is not solely a modern evil, that if Fricker is correct, then there would be motivation to restrict a group's hermeneutic participation in social life.

Historically, this injustice was committed against women, but there is not much reason to think that it was committed only against women.  As an injustice, this is a source of evil in that it is an experience that is direct an intuitive by the victim of the evil [@russ16, 1]. More specifically, it is a representation of the one kind of evil. This is the kind of evil that is evil specifically because it deceives. This kind of evil was represented artistically in medieval beastiaries through the image of the manticore.

## Hermeneutic Marginalization

> "Beastiaries are composed of different hermeneutic codes which are mapped to different sensitive levels, that is, from the level describing mere anatomy we may turn to the one
dealing with ethical-philosophical consideration; and further turn to the one on moral
perspectives which are later complemented with the theological ones (Voisenet 2020,
pp. 321–25). In all these cases, the fields of word and those of image are intertwined (Kay
2017). In the end, XII–XIII century bestiaries, books on natural history and encyclopedias
allow us to access a world where both the creative power of goodness and evil are present:
The excellence of divine creation and the subtlety of diabolic action play a role."

### Types of hermeneutic codes

* 'Mere' anatomy
* Ethical-philosophical considerations
* Moral perspectives
* Theological perspectives

## What is a hermeneutic code in these cases?

A way to understand this may be arts divergent foci on simple reality and complex reality. Between these two representations is a set of norms culturally and socially constructed to guide the representation of the human condition: experience, knowledge, and beliefs. The conflict here is between God and the devil. What specifically are the adverse actions, carried out by the one against the other in this space? Jesus' death, burial, and resurrection is at one level an adverse action carried out by the work of the devil, yet at the same time, it is also symbolic of the ultimate victory, that of God over sin, death, hell, and the grave.

> "Its commitment with reality is undeniable yet the reality which it at
tempts to represent is so complex and vast that the limits between what is and what is not,
between what we believe and what we know, between what we are and what we wish to
be, are often blurred (Cronin 1941). Medieval ars is much more than a set of norms which
ought to be followed to produce something that can be called art. "

> "Art, so understood, is a necessary element in the configuration of human
condition in terms of experience, knowledge, and beliefs.
It is within this context where the action of God and that of the devil provide one of
the most profound lectures of reality."

The manticore, but many accounts, was initially found in Persian literature as early as the 5th and 4th century BC. In his Photius, the Greek historian working for the Persian court describes the Manticore as a beast with red skin, as large as a lion, three rows of teeth, human like face and the tail of a scorpion. Later writers would quote Ctesias' description of the Manticore, adding emphasis on its dietary habits, including that it ate men. Though it is likely that many of these descriptions were of predatory animals passed by word of mouth until they reached the Persian king's court, what is even more important is the way in which these descriptions began to stand in for imageries of evil in the Medieval literature.

> By the union of the hyæna with the Æthiopian lioness, the and destructive nature of the red ants on the coast of Guinea ; and it is not improbable that it is to these that Pliny alludes.^[See B. v. c. 33.; This is mentioned by Ælian, Anim. Nat. B. xv. c. 26.-B. The scolopendra is one of the multipede insects.; Aristotle, De Gener. Anim. B. iii. c. 6, and Hist. Anim. B. vi. c. 32, accounts for the vulgar error, by stating that the hyæna has a peculiar structure of the parts about the anus, which might, to an unpractised eye, give the idea, that it possesses the generative organs of both sexes. Ælian,; Anim. Nat. B. i. c. 25, and Oppian, Cyneget. B. iii. c. 289, have adopted this erroneous opinion. What is said respecting the hyæna, in the remain- ing part of this Chapter, is mostly without foundation.-B.; We have had some account given of the mantichora, in c. 30. The mantichora and the corocotta are altogether imaginary.-B. Cuvier, in Chap. 47.] corocotta is produced, which has the same faculty of imitating the voices of men and cattle. Its gaze is always fixed and immoveable ; it has no gums in either of its jaws, and the teeth are one continuous piece of bone ; they are enclosed in a sort of box as it were, that they may not be blunted by rub- bing against each other. Juba informs us, that the mantichora of Æthiopia can also imitate the human speech. [The Natural History of Pliny the Elder, p. 313, ch. 45 --- The corocotta; the mantichora]

Evil is often given descriptions of more recognizable items such as animals. One such description exists in the document *Libellus in modum Symboli* written by the bishop Pastor for the Council of Toledo in 447 [@alda34]. Evil is described as hideous, black, gigantic, fetid, horned and crowned with donkey ears and claws etc. Often accompanying such descriptions are dispositions and abilities. For instance, the evil guarding hell has often been said to have the magnetic ability to attract other objects and that it can annihilate objects like lightning [@much00, 27-28].

* Aristotle's History of Animals

> None of these genera have a double row of teeth. But, if we may believe Ctesias, there are some which have this peculiarity, for he mentions an Indian animal called martichora, which had three rows of teeth in each jaw; it is as large and as rough as a lion, and has similar feet, but its ears and faceare like those of a man; its eye is grey, and its body red; it has a tail like aland scorpion, inwhich there is a sting; it darts forth the spines with which it is covered instead of hair, and it utters a noise resembling the united sound of a pipe and a trumpet; it is not less swift of foot than a stag, and is wild, and devours men. [p. 30-31; also see [Aristotle, History of Animals 8.28, 605b22-606a10](https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0086.tlg014.1st1K-grc1:8.28/)]

There is an important distinction here between familiar and unfamiliar images.  It is not clear how the medievalist went about deciding when to use familiar imagery and when to use unfamiliar imagery.

> Ctesias informs us, that among these same Æthiopians, there is an animal found, which he calls the mantichora ; it has a triple row of teeth, which fit into each other like those of a comb, the face and ears of a man, and azure eyes, is of the colour of blood, has the body of the lion, and a tail ending in a sting, like that of the scorpion. Its voice resembles the union of the sound of the flute and the trumpet ; it is of excessive swiftness, and is particularly fond of human flesh.^[This description of the mantichora appears to be taken from the Indica of Ctesias ; it has been also adopted by Aristotle and Ælian, but they have qualified their accounts by some expressions of doubt, which are omitted by Pliny. It has been conjectured, that Ctesias took his descrip- tion from the hieroglyphic figures in his time, probably common in the East, and still found in the ruins of the Assyrian and Persian cities, Ni- neveh and Persepolis, for instance.-B.] [p. 280]

* Aristotle's History of Animals

By combining familiar traits with unfamiliar ones, it is perhaps easier to express the concept that evil is immaterial rather than material. The immaterial attributes then become ones which we may be familiar with, but are at times difficult to identify. Moral initially alludes to why these decisions were made. He points out that the symbols would be useful for individuals express more conceptual images such as pain, death, the struggle between good and evil. But importantly here, are the roles in which such symbols play in our abilities to directly intuit the expressed attributes, death, pain, etc.

* Bodleian Library MS.

:::: {.columns}

::: {.columns}

::: {.column width="100%"}
<iframe src="https://digital.bodleian.ox.ac.uk/embed/iframe/?url=https%3A%2F%2Fdigital.bodleian.ox.ac.uk%2Fobjects%2Feb0735a3-e8ee-4104-b111-51d18a13b78b%2Fsurfaces%2F47fdb9fa-11fa-4f08-b488-4fff023a6792%2F" width="100%" height="600px" allowfullscreen frameborder="0"></iframe>

Fol. 009v – Early folio (text/other beast)
:::

::: {.column width="100%"}
<iframe src="https://digital.bodleian.ox.ac.uk/embed/iframe/?url=https%3A%2F%2Fdigital.bodleian.ox.ac.uk%2Fobjects%2Fe6ad6426-6ff5-4c33-a078-ca518b36ca49%2Fsurfaces%2F86bee6cc-7b69-44b6-b264-579f4ac6576c%2F" width="100%" height="600px" allowfullscreen frameborder="0"></iframe>

Fol. 025r – Classic manticore (MS. Bodl. 764)
:::
:::

::: {.column width="100%"}
<iframe src="https://digital.bodleian.ox.ac.uk/embed/iframe/?url=https%3A%2F%2Fdigital.bodleian.ox.ac.uk%2Fobjects%2Fecf96804-a514-4adc-8779-2dbc4e4b2f1e%2Fsurfaces%2Fee2bf789-7152-449b-9760-fa864718e2d0%2F" width="100%" height="600px" allowfullscreen frameborder="0"></iframe>

Fol. 022v – Manticore variant (MS. Ashmole 1511)
:::

::::

Should we become confronted by outcomes commonly associated with them, by describing their immaterial natures, we are given a hermeneutic tool with which to deal with that event. For instance, evil personified as the devil has been described as a being which seduces, deceives, acts harmfully and violently and can be lethal. The proper symbology then will enable us to directly intuit the attributes of evil. In the following section, it will be helpful to look at some plausible effects of evil.

# Constructing the Emotions

In his book *Gut Reactions*, Jesse Prinz points out several links between emotion and cognitive potential. Considering cognitive systems such as categorization, memory, attention, and reasoning, such systems have been shown to be affected by an individual's emotion states.

1. "It is easier to recall events when we are in emotional states that are congruent with the events that we are recalling" (Bower, 1981)
2. "Positive emotions tend to promote the user of stereotypes" (Bless, Schwarz, & Kemmelmeier, 1996)
3. "Positive emotions tend to help us reason in ways that are open-minded, optimistic, and creative", for instance, "we have an easier time solving problems that require novel applications of familiar materials" (Isen, Daubman, & Nowicki, 1987).
4. "Negative emotions tend to promote more narrow attentional focus. Anxiety makes us attend to threatening objects" (MacLeod & Mathews, 1991; Ohman, Flykt, & Esteves, 2001).

Which of these are related to self-understood notions of identity? Consider 2-4. In notions of identity, we can ask questions such one's understanding of their identity:

1. Narrative Identity
2. Personal Identity
3. Personal identity as response to what emotions one feels and when
4. What emotions one feels is related to important cognitive processes

Wendy @layb18 proposes a criticism of black authenticity and what she calls commodified realness. According to Laybourn, identity is sold to a broader public as black authenticity. But we can broaden out this criticism to ask what any specific notion of authenticity entails. What is authentically male, female, ethnic, or nationality. This criticism is centered around the effects of what she calls *controlling images* in popular media. Of deep concern here, is that many of the members of the communities depicted by such images consider aspects of these images to be authentic representations and not in themselves harmful. Yet too, this is also a common trope, as old as society.

I present this case as an example of a paradigmatic concept of hermeneutic injustice. It is not clear just what aspects of the member's lives are represented, nor specifically which images are harmful if such images are accepted as representative. An important question here has to do with the relationship between popular narratives that contain these images, and personal identity. One approach argues that we are defined by the stories we accept about ourselves, but this is controversial.

In cases of marginal representation, it is not clear just what aspects of the member's lives are represented, nor specifically which images are harmful if such images are accepted as representative. An important question here has to do with the relationship between popular narratives that contain these images, and personal identity. One approach argues that we are defined by the stories we accept about ourselves, but this is controversial.

It is not necessarily clear where to find the literature on specifically what is at issue here. Because of this, I think it will be helpful to start with something of an analogy, specifically one from the popular narrative.

In the newest Wicked screen adaptation, there is an underlying story line. The protagonist, the 'wicked' witch finally comes to accept that she will never be accepted by the broader public and as such, will always stand out as a scapegoat of sorts owing to her dark green skin. Therefore she fully leans into her 'wicked' persona.

However, perhaps a detail which could not be included as prominently in Gregory Maguires 1995 novel. The amazing actress, Cynthia Erivo, is an African American with especially prominent African, accentuated owing to the excellent applied makeup and superb acting by Evrivo, features. Through both movies, it is obvious that she isn't green in reality, but African American. We see the story of the witch as a case of othering. As such, especially poignant was the moment when Dorothy, believing the witch can be killed throws a bucket of water on her, an old racist trope about African Americans and bathing.

It is a fortunate accident I suppose, director John M. Chu taking perfect advantage of the fact that the witch in the original dies having had a bucket of water thrown onto her. The witch, fully adopting her role, seemingly for the good of the people of Oz, 'dies', but in the fiction, merely goes into hiding.

Ultimately Elphaba and Prince Fiyero, turned Straw man, strike out to the desert after her sacrificial death accepting that they will forever be scapegoats should they choose to stay in Oz.

So while we might think that medieval art has no place in a discussion about epistemic injustice, I argue that the depiction of the fictional beast called the manticore, as a personification of deception lends credibility to this claim. According to the modern function of art summed up by Jonathan @gilm20, art's function is oriented to ends such as pleasure, entertainment, and absorption [@gilm20, 132]. Conversely, the medieval function of art is directed at more orthodoxical ends intending to motivate desirable behaviors and behavioral responses. On one account of this deception, a person holds false beliefs about themselves. These beliefs stem from hermeneutically unjust environments where the individual lacks access to resources that would lead to accurate self-understanding and moral beliefs. Such beliefs are rooted in irrational actions performed by the individual.

As an artistic object, the Manticore is a fictionalized beast that was born in Persian art and literature sometime around its cultural zenith. It at once symbolizes evil, death and hell, but in medieval religious art, came to symbolize the power of Christ over death and hell.

In the Summa Theologica, Thomas Aquinas defends the view of art as a form of right reason [I-II, Q.57]. There is a distinction here between right reason for making objects, and right reason for doing good actions. But a better analogy here is 'making actions with good outcomes'. We should first focus on the point that important to both of these activities, is the right use of one's cognitive faculties.

The difference lies in the produced object, whether an action or thing. But here, we should pause momentarily or we risk conflating two senses of right action. In the ancient context, right action would more probably be used to reference actions that align with a dominant organizational structure, for instance the Catholic church. In our own modern context, we are less apt to recognize a singular dominant moral authority. This presents a problem since we would want to say something more akin to 'beneficial', or 'productive' action where 'benefit' and 'product' are more expressive of individual tastes and desires.

Considering a product that is produced, the desired outcome of the activity of art, it is not clear what it is exactly, that we collectively care about in the case of art then. When it comes to what is produced by artistic endeavor, it is not clear whether a normative account should include a material commodity, or a desired outcome apart from a material commodity. When we think about what a good artistic endeavor entails, in the modern conception, there is typically some monetary component. For instance, an admirable artistic endeavor at the center of an advertising campaign would ideally result in increased revenue for the advertising clients and increased business for the advertiser.

However, the medieval conception of an admirable artistic endeavor consists of outcomes which invoke some kind of behavior. Whether dispositions or actions, ultimately there is a desire for an intended outcome as it correlates specifically with a human actor. @harr11 argues for instance, that Elizabeth Gaskell's novel *Mary Barton: A Tale of Manchester Life* was in part responsible for the UK's expanded social safety net. Gaskell represented the suffering and distress experienced by the working poor in a way that allowed her upper-class Victorian audience to empathize with the lower social classes [@harr11, 258]. For instance, we might think that a good artist produces items of great monetary value. But using the medieval depiction as expressed above, it seems that a good artist instead motivates an actor to behave in a way that produces good outcomes. The common contemporary understanding considers various perspectives. However, it is important to understand the two important points here.

@pine21 argues that this is because art's purpose in the middle ages is to represent reality. It is one thing to accurately and factually represent a tree, however, Pinero is talking about more complex reality, especially moral reality.

One example of medieval representations of moral reality include the Persian Manticore.

The manticore as depicted in medieval art is said to represent evil. There are several ways in which some art object may represent more complex realities. One may think that the purpose of a painting is to reflect the experiences one had during a war, or peace time event. Such a painting may express the given facts of the case, for instance an artist could paint the signing of the Magna Carta. If the painting were painted by an artist who was alive to witness the signing of the Magna Carta, then the artist would merely be representing contemporary reality. If the art were not alive at the time, then we could argue that the artist is representing historical reality. If the artist is relying on trusted sources that are well-known, then this would be different than if the artist were imagining an event which not many direct sources exist.

But an artist can represent a projection of reality as well when the reality they want to convey is obscure, not well known, highly contested etc.

> By definition, medieval art implies metaphysical aspirations and normative elements (De Bruyne 1959). Its commitment with reality is undeniable yet the reality which it attempts to represent is so complex and vast that the limits between what is and what is not, between what we believe and what we know, between what we are and what we wish to be, are often blurred. (Cronin 1941)

Here, the artist can represent facts as they believe them to be, or as they wish them to be. It is this latter motivation that Pinero suggests motivated medieval artwork representing the manticore.
