---
title: "Philosophical Pedagogy and Star Citizen"
date: '2024-10-01'
---

The BGG foundation is dedicated to empowering youth through video-gaming. We have recently begun to develop a 12-week philosophy course that uses Mass-Multiplayer video games to help students to better understand the concept of ethical reasoning. This includes understanding which considerations shape their ethical responses (Croft), the ethical dimensions of meaning and purpose foundational to philosophical tradition, be able to think independently and creatively about the human condition (e.g., living-well, moral value, intellectual virtue).

The Love Ethic project by Notre Dame sums this up nicely:

“Love Ethic Collaborations are open to scholars who are conducting a substantial research project that advances our theoretical understanding of a dimension of love-based ethical frameworks.”

What is one way to advance our theoretical understanding of a dimension of love-based ethical frameworks?

I want to have students model ethical frameworks in open world game play. Why?

> What both *metis* and Platonic self-sufficiency omit is a picture of excellence that is shown to us in the traditional image of *arete* as plant: a kind of human worth that is inseparable from vulnerability, an excellence that is in its nature other-related and social, a rationality who nature it is *not* to attempt to seize, hold, trap, and control, in whose values openness, receptivity, and wonder play an important part. [@nuss86i, 20]

This is a reliance on external objects taht will recive "the excellent activity", others to receive the agent's generosity, good activity connected with citizenship and political attachment as well as personal love and friendship [@nuss86i, 343].

It is largely been argued that these relationships can be cultivated through narratives.

Our program will use video games to develop philosophical explorations in the areas of ethics and aesthetics for high school and junior undergraduate students. Tragedy and other art enable us to appreciate how our ethical commitments can sometimes conflict with more fundamental commitments: moral attachments, meaningful relationships (parent / child, spouse etc). We argue that when combined with carefully selected reading materials, role-playing in virtual video-game environments can double as executable thought experiments that resemble critical dilemmas in assigned literature. These would, for instance, model ethical dilemmas and cultivate moral reasoning by using MMO’s abilities to model and create felt presence, leading participants through sequences of events which reflect how one experiences the real world in all its moral philosophical complexity.

1. High School Ethics Laboratory: a 12-week course on philosophical pedagogy and video games
   1. Focus more on ethical experiences and reasoning
2. Junior Undergraduate Ethics Laboratory: a 12-week course on philosophical pedagogy and video games
   1. Focus is more on standard introductory ethics and introduction to philosophy
3. Edited Volume on Philosophical Pedagogy and Star Citizen / or MMOs
   1. Invite authors who use video games to join an org in Star Citizen, then contribute a paper to the volume
4. First of its kind, a virtual conference on philosophical pedagogy and video games in Star Citizen

## Extended Reality and Classroom Instruction, Bridging the Technology Gap

### The Extension of Virtual Reality, Virtue Reality

Rebeka Davis

>  This chapter aims to increase educators’ effectiveness for using VR in the
classroom by helping them leverage the affordance of presence in learning experiences. Research findings on
the sense of presence are utilized to provide structure for an exploration of considerations and questions educators should address as they plan virtual experiences for learners. Because devices come and go so quickly, there are not specific recommendations for devices or activities; rather, a structured guide for considering the affordance of the sense of presence when teaching and learning with VR is offered.

* What educators should think about

* Questions one should ask about learners and devices

* how to relate to learners through experience

### Removing Barriers of Space and Time to Immerse Students in Virtual Learning Environments

James Hutson

>  VR has the potential to support other student populations who may be rural or
low-income, thus providing greater equity, inclusivity, and access to overcome the socioeconomic restrictions underrepresented students face in their development of global citizenship. To facilitate the effective use and adoption of VR, the results of multiple case studies using a concurrent triangulation design are presented, which outline the pedagogical strategies that may be adopted in a number of areas.

* Scaffold immersive learning experiences
* Aligning learning activity based on participants and instrutors

#### For further research

> The results from the two studies confirm earlier research on the positive correlation between the use of VR and increased enjoyment in learning and improved motivation, which leads to deeper learning and long-term retention of material (Brownridge, 2020; Cheung et al. 2013; Huang et al., 2010; Hussein & Nätterdal, 2015; Jacobson & Lewis, 2005; Rizzo
et al. 2006; Sharma et al., 2013).

### Theory of Learning in Immersive Environments and 4E Cognition

 GREGORY MCGOWIN
University of Central Florida, USA
 gmcgowin@knights.ucf.edu
 STEPHEN M. FIORE
University of Central Florida, USA
 KEVIN ODEN
 Lockheed Martin, US

> there is a troubling gap between the development of I-VR for education and training and the learning theories that ensure its efficacy. To address this need, we provide a theoretical lens to help the education and training communities evaluate exist
ing and future research in I-VR. Specifically, we will review technological innovations that have made I-VR
more advanced and draw from research from both the cognitive and learning sciences to assess their effec
tiveness as learning affordances.

1. Analyze Current Research on I-VR
   1. Move beyond cognition as info processing (Hutto & Abrahamson, 2022, p. 40),
   2. link body, in environment with cognition (Macrine & Fugate, 2022), e.g., extended mind  Clark and
Chalmers (1998)
   3. Cognition extendeds from body first, to tech objects and social interactions  (Aagaard, 2021).
2. Demonstrate Practical value of theoretical demonstrations
   1. I.e., doing rather than only observing
3. Contextualize theoretical demonstrations through example implementations
4. Help stakeholders generate better designed studies for education and training communities

### Multiple Worlds: Adolescents, New Digital Media, and Shifts in Habits of Mind

Margaret Weigel* and Celka Straughn, With Howard Gardner and Carrie James

The Developing Minds and Digital Media Project1

HARVARD UNIVERSITY
Project Zero
124 Mt. Auburn St.
Cambridge, MA 02138
margaret_weigel@pz.harvard.edu
 celka_straughn@pz.harvard.edu

> Researchers on The Developing Minds and Digital Media project interviewed forty experienced and articulate high school educators (drawn from sixteen elite New England schools with an average of twenty-three years in the classroom) about what types of changes, if any, they had observed in their students over time. Our team devoted special attention to changes in routine (non-social) cognition, social cognition, and moral and ethical priorities as they relate to new digital media (NDM) engagement. The project’s findings are nuanced and encompass a wide range of behaviors. To capture our conclusions succinctly, we determined that NDM encourage certain tasks and behaviors and discourage others – the archetypal ‘mixed blessing.’ Much of the tension derives from how students deal with the often overwhelming volume of information and practices of social networking online.

### “It’s Just a Game”—Ethical Reasoning within Virtual Worlds

James Croft

> “How do Boston-area youth (15–25) reason about ethical dilemmas occurring within virtual
worlds such as ‘World of Warcraft’?”; and “Which considerations seem to shape their ethical
responses?” In semi-structured interviews 27 young people were presented with an ethical
dilemma: subjects were asked to imagine that they had been playing an online multiplayer game
of around 30,000 players for two weeks. Within the imagined game, they are asked whether or
not they would join their online friends in selling “Pseudogems”—worthless items that are
thought to be valuable by new players—to others in the gameworld. The responses of our
participants suggest that most young people (13 of 27) would sell the gems, while 8 would not, with 6 giving a mixed response.
