---
title: "Beasts of Burden and Right Reason"
#subtitle: "Beasts of Imagination and Right Reason"
date: '2025-12-06'
---

We might think that medieval art has no place in a discussion about epistemic injustice, but I argue that the depiction of the fictional beast called the manticore, as a personification of deception lends credibility to this claim. According to the modern function of art summed up by Jonathan @gilm20, art's function is oriented to ends such as pleasure, entertainment, and absorption [@gilm20, 132]. Conversely, the medieval function of art is directed at more orthodoxical ends intending to motivate desirable behaviors and behavioral responses. On one account of this deception, a person holds false beliefs about themselves. These beliefs stem from hermeneutically unjust environments where the individual lacks access to resources that would lead to accurate self-understanding and moral beliefs. Such beliefs are rooted in irrational actions performed by the individual.

It does this by contrasting the concept of hermeneutic justice as popularized by Miranda @fric07 but developed by earlier feminists. We might think that medieval art has no place in a discussion about epistemic injustice, but I argue that the depiction of the fictional beast called the manticore, as a personification of deception lends credibility to this claim. According to the modern function of art summed up by Jonathan @gilm20, art's function is oriented to ends such as pleasure, entertainment, and absorption [@gilm20, 132]. Conversely, the medieval function of art is directed at more orthodoxical ends intending to motivate behaviors and behavioral responses.

As an artistic object, the Manticore is a fictionalized beast that was born in Persian art and literature sometime around its cultural zenith. It at once symbolizes evil, death and hell, but in medieval religious art, came to symbolize the power of Christ over death and hell.

In the Summa Theologica, Thomas Aquinas defends the view of art as a form of right reason [I-II, Q.57]. There is a distinction here between right reason for making objects, and right reason for doing good actions. But a better analogy here is 'making actions with good outcomes'. We should first focus on the point that important to both of these activities, is the right use of one's cognitive faculties.

The difference lies in the produced object, whether an action or thing. But here, we should pause momentarily or we risk conflating two senses of right action. In the ancient context, right action would more probably be used to reference actions that align with a dominant organizational structure, for instance the Catholic church. In our own modern context, we are less apt to recognize a singular dominant moral authority. This presents a problem since we would want to say something more akin to 'beneficial', or 'productive' action where 'benefit' and 'product' are more expressive of individual tastes and desires.

Considering a product that is produced, the desired outcome of the activity of art, it is not clear what it is exactly, that we collectively care about in the case of art then. When it comes to what is produced by artistic endeavor, it is not clear whether a normative account should include a material commodity, or a desired outcome apart from a material commodity. When we think about what a good artistic endeavor entails, in the modern conception, there is typically some monetary component. For instance, an admirable artistic endeavor at the center of an advertising campaign would ideally result in increased revenue for the advertising clients and increased business for the advertiser.

However, the medieval conception of an admirable artistic endeavor consists of outcomes which invoke some kind of behavior. Whether dispositions or actions, ultimately there is a desire for an intended outcome as it correlates specifically with a human actor. @harr11 argues for instance, that Elizabeth Gaskell's novel *Mary Barton: A Tale of Manchester Life* was in part responsible for the UK's expanded social safety net. Gaskell represented the suffering and distress experienced by the working poor in a way that allowed her upper-class Victorian audience to empathize with the lower social classes [@harr11, 258]. For instance, we might think that a good artist produces items of great monetary value. But using the medieval depiction as expressed above, it seems that a good artist instead motivates an actor to behave in a way that produces good outcomes. The common contemporary understanding considers various perspectives. However, it is important to understand the two important points here.

@pine21 argues that this is because art's purpose in the middle ages is to represent reality. It is one thing to accurately and factually represent a tree, however, Pinero is talking about more complex reality, especially moral reality.

One example of medieval representations of moral reality include the Persian Manticore.

The manticore as depicted in medieval art is said to represent evil. There are several ways in which some art object may represent more complex realities. One may think that the purpose of a painting is to reflect the experiences one had during a war, or peace time event. Such a painting may express the given facts of the case, for instance an artist could paint the signing of the Magna Carta. If the painting were painted by an artist who was alive to witness the signing of the Magna Carta, then the artist would merely be representing contemporary reality. If the art were not alive at the time, then we could argue that the artist is representing historical reality. If the artist is relying on trusted sources that are well-known, then this would be different than if the artist were imagining an event which not many direct sources exist.

But an artist can represent a projection of reality as well when the reality they want to convey is obscure, not well known, highly contested etc.

> By definition, medieval art implies metaphysical aspirations and normative elements (De Bruyne 1959). Its commitment with reality is undeniable yet the reality which it attempts to represent is so complex and vast that the limits between what is and what is not, between what we believe and what we know, between what we are and what we wish to be, are often blurred. (Cronin 1941)

Here, the artist can represent facts as they believe them to be, or as they wish them to be. It is this latter motivation that Pinero suggests motivated medieval artwork representing the manticore.
